Django/Study_Notes - V1.5/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [  # url 模型
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^users/', include('users.urls', namespace='users')),
    path(r'', include('learning_logs.urls', namespace='learning_logs')),  # 命名空间便于同项目中的其他URL区分开来，有利于项目扩展
]

Django/Study_Notes - V1.5/learning_logs/urls.py
# -*- coding: utf-8 -*-
#  @ Date   : 2019/5/20 13:14
#  @ Author : ©RichardLau_Cx
#  @ file   : Richard.py
#  @ IDE    : PyCharm

"""定义learning_logs的URL模式"""  # 文档字符串

from django.conf.urls import url
from django.urls import path, re_path
from . import views

app_name = 'learning_logs'  # 应用命名空间

urlpatterns = [
    # 网址样式

    # 主页
    re_path(r'^$', views.index, name='index'),

    # 显示所有主题
    # re_path(r'^topics/$', views.topics, name='topics')
    path(r'topics/', views.topics, name='topics'),
    re_path(r'^topic/(?P<topic_id>\d+)/$', views.topic, name='topic'),  # 其中的正则相当于分组捕获，将值存至topic_id中
    re_path(r'^topic/(?P<topic_id>\d+)/whether_public/$', views.whether_public, name='whether_public'),
    re_path(r'^new_topic/$', views.new_topic, name='new_topic'),  # 用于添加新主题的网页
    re_path(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    re_path(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
]

Django/Study_Notes - V1.5/users/urls.py
# -*- coding: utf-8 -*-
#  @ Date   : 2019/5/20 13:14
#  @ Author : ©RichardLau_Cx
#  @ file   : Richard.py
#  @ IDE    : PyCharm

"""定义urls的URL模式"""  # 文档字符串

from django.urls import path, re_path
from django.contrib.auth.views import LoginView
from . import views

app_name = 'users'

urlpatterns = [
    # 登陆页面
    # re_path(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),  # 1.0 版本表示
    re_path(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),  # 2.0 版本表示

    # 注销页面
    re_path(r'^logout/$', views.logout_view, name='logout'),

    # 注册页面
    re_path(r'^register/$', views.register, name='register'),
]

Django/Study_Notes - V1.5/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Topic(models.Model):
    """
    用户学习的主题
    """
    # 默认主键id，会自动生成
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    public = models.BooleanField(default=False)  # 是否公开主题
    owner = models.ForeignKey(User, on_delete=models.CASCADE)  # 若执行删除，将以级联的方式进行

    def __str__(self):
        """
        返回模型（主题名）的字符串表示
        :return: test
        """
        return self.text


class Entry(models.Model):
    """
    学到的有关某个主题领域的具体知识（条目）
    """

    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)  # 外键实例，删除是以级联的方式
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)  # 自动添加当前时间戳

    class Meta:
        verbose_name_plural = 'entries'  # 详细的多个条目名

    def __str__(self):
        """
        返回模型的字符串表示（界面上的显示）
        :return: 对应对象实例的描述信息
        """
        if len(self.text[:]) <= 50:  # TODO 待测试
            return self.text

        else:
            return self.text[:50] + "..."

Django/Study_Notes - V1.5/learning_logs/forms.py
# -*- coding: utf-8 -*-
#  @ Date   : 2019/5/20 13:14
#  @ Author : ©RichardLau_Cx
#  @ file   : Richard.py
#  @ IDE    : PyCharm


from django import forms

from .models import Topic, Entry


class Topic_Form(forms.ModelForm):
    class Meta:
        model = Topic  # 根据模型Topic创建一个表单
        fields = ['text']  # 表单所含字段：text
        labels = {'text': ''}  # Django不要为字段text生成标签


class Entry_Form(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}  # 为test字段定义了一个空标签
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}  # 修改默认HTML小部件，通过Django使用forms.Textarea，定制字段test输入小部件

Django/Study_Notes - V1.5/learning_logs/views.py
from django.shortcuts import reverse, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404

from .tools import check_topic_owner, check_topic_public
from .forms import Topic_Form, Entry_Form
from .models import Topic, Entry


# Create your views here.


def index(request):
    """学习笔记的主页"""
    return render(request, 'learning_logs/index.html')


# @login_required
def topics(request):
    """显示所有的主题"""

    # topic_all = Topic.objects.filter(owner=request.user).order_by('date_added')
    topic_all = Topic.objects.order_by('date_added')
    context = {'topics': topic_all}  # 通过字典的键，来引用列表值

    return render(request, 'learning_logs/topics.html', context)


# @login_required
def topic(request, topic_id):
    """
    显示单个主题，以及所有的条目
    :param request: 服务器请求
    :param topic_id: 主题id
    :return:
    """

    # topic_single = Topic.objects.get(id=topic_id)
    topic_single = get_object_or_404(Topic, id=topic_id)

    # 确认请求的主题，是否属于当前用户
    # check_topic_owner(request, topic_single)
    check_topic_public(request, topic_single)
    entries = topic_single.entry_set.order_by('-date_added')  # 减号指定按照降序排序
    context = {'topic': topic_single, 'entries': entries}  # 数据环境字典

    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    """
    添加一个新主题
    :param request:
    :return:
    """
    if request.method != 'POST':  # 相当于可能是GET请求
        # 未提交数据：创建一个空表单
        form = Topic_Form()

    else:
        # POST 提交了数据，对数据进行处理
        form = Topic_Form(request.POST)

        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user  # 当前用户为新添所有者
            new_topic.save()

            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context = {'form': form}

    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    """
    在特定的主题当中，添加新条目
    :param topic_id:
    :param request:
    :return:
    """
    topic = Topic.objects.get(id=topic_id)  # 获取主题对象

    if request.method != 'POST':  # 相当于可能是GET请求
        # 未提交数据：创建一个空表单
        form = Entry_Form()

    else:
        # POST 提交了数据，对数据进行处理
        form = Entry_Form(data=request.POST)

        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.owner = request.user
            new_entry.save()

            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}

    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """
    编辑既有的条目
    :param request:
    :param entry_id:
    :return:
    """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    # check_topic_owner(request, topic)
    check_topic_public(request, topic)

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = Entry_Form(instance=entry)

    else:
        # POST提交的数据，对数据进行处理
        form = Entry_Form(instance=entry, data=request.POST)

        if form.is_valid():
            form.save()

            return HttpResponseRedirect(reverse('learning_logs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}

    return render(request, 'learning_logs/edit_entry.html', context)


@login_required
def whether_public(request, topic_id):
    """
    调整主题是否为公开
    :param request:
    :return:
    """
    public = request.POST.get("public")  # 接收到的是字符串形式
    topic = Topic.objects.get(id=topic_id)  # 获取主题对象
    # print(type(public))  <class 'str'>

    if public == "True":
        public_s = "public"
        public = True

    else:
        public_s = "private"
        public = False

    topic.public = public
    topic.save()  # 保存模型对象
    # print(topic.public)

    # topic_single = Topic.objects.get(id=topic_id)
    topic_single = get_object_or_404(Topic, id=topic_id)

    check_topic_public(request, topic_single)
    entries = topic_single.entry_set.order_by('-date_added')  # 减号指定按照降序排序
    context = {'topic': topic_single, 'entries': entries, 'public_s': public_s}  # 数据环境字典

    return render(request, 'learning_logs/topic.html', context)

Django/Study_Notes - V1.5/learning_logs/templates/learning_logs/base.html
{% load bootstrap3%}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>Study Notes</title>

		{% bootstrap_css %}
		{% bootstrap_javascript %}
	</head>

	<body>
		<!-- Static navbar -->
		<nav class="navbar navbar-default navbar-static-top">
			<div class="container">

				<div class="navbar-header">
					<button id="nav-btn" type="button" class="navbar-toggle collapsed"
					        data-toggle="collapse" data-target="#navbar"
					        aria-expanded="false" aria-controls="navbar">
					</button>
					<a class="navbar-brand" href="{% url 'learning_logs:index' %}">Study Notes</a>
				</div>

				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li> <a href="{% url 'learning_logs:topics' %}">Themes</a> </li>
					</ul>

					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
						<li><a>Hi, {{ user.username }}, welcome!</a></li>
							<li><a href="{% url 'users:logout' %}">log out</a> </li>
						{% else %}
							<li><a href="{% url 'users:login' %}">log in</a> </li>
							<li><a href="{% url 'users:register' %}">register</a> </li>
						{% endif %}
					</ul>
				</div><!--/.nav-collapse -->

			</div>
		</nav>
		<div class="container">

			<div class="page-header">
				{% block header %}{% endblock header %}
			</div>
			<div>
				{% block content %}{% endblock content %}
			</div>

		</div><!-- /container -->

	</body>
</html>

Django/Study_Notes - V1.5/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Modify an entry: </h2>
{% endblock header %}

{% block content %}

    <h3>
	    <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
      <small>(Edit entry): </small>
    </h3>



    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

	      {% buttons %}
          <button name="submit" class="btn btn-primary">save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

Django/Study_Notes - V1.5/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
	<div class="jumbotron">
		<h1>Real - time learning process.</h1>
		<br>
		<h3>欢迎刘晨旭的家人们莅临指导！</h3>
	</div>
{% endblock header %}

{% block content %}
	<h2>
		<a href="{% url 'users:register' %}">Register an account</a>:
		When you register the account, can let you have your own learning records, and some of them listed on your journey of learning.
	</h2>
	<h2>
		When you get your own theme, you can add some entries in for it
	</h2>
	<br><br><br>
    <p>Learning Log helps you keep track of your learning, for any topic you're learning about!</p>
{% endblock content %}

Django/Study_Notes - V1.5/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Generates a new entry: </h2>
{% endblock header %}

{% block content%}

    <h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a> </h3>


    <form action="{%  url 'learning_logs:new_entry' topic.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

	      {% buttons  %}
		      <button name="submit" class="btn btn-primary">add entry</button>
	      {% endbuttons  %}

    </form>

{% endblock content %}

Django/Study_Notes - V1.5/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
	<h2>Generate a new theme: </h2>
{% endblock header %}

{% block content%}
    <form action="{%  url 'learning_logs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}

	      {% buttons %}
	        <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
    
    </form>

{% endblock content %}

Django/Study_Notes - V1.5/learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap3 %}

{% block header %}
      <form action="{% url 'learning_logs:whether_public' topic.id %}" method="post" class="form">
        {% csrf_token %}
        <label>
	        <big>{{ topic }}&nbsp;</big>
	        <small>
	          <select name="public">
		          {% if topic.public %}
		            <option value={{ topic.public}}>public</option>
		          {% else %}
			          <option value={{ topic.public}}>private</option>
		          {% endif %}

	            <option value=False>private</option>
					    <option value=True>public</option>
				    </select>
	        </small>

        {% buttons %}
	        <br>
	        <button name="submit" class="btn btn-primary">modify</button>
        {% endbuttons %}
        </label>
      </form>

{% endblock header %}

{% block content %}

{#  <p>Entries: </p>#}

  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>
  </p>

    {% for entry in entries %}
      <div class="panel panel-default">

        <div class="panel-heading">
					<h3>
						{{ entry.date_added | date:'M d, Y H:i' }}
						<small>
							<a href="{% url 'learning_logs:edit_entry' entry.id %}">edit entry</a>
						</small>
					</h3>
        </div>

	      <div class="panel-body">
		      {{ entry.text | linebreaks }}
	      </div>

      </div> <!-- /panel -->

    {% empty %}
          There are no entries for this topic yet.
    {% endfor %}

{% endblock content %}

Django/Study_Notes - V1.5/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header%}
	<h1>Topics</h1>
{% endblock header %}

{% block content %}

    <ul>
        {% for topic in topics %}
            <li>
              <h3>
	              <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
              </h3>
            </li>
        {% empty %}
          <li>No topics have been added yet.</li>
        {% endfor %}
    </ul>

		<h3>
			<a href="{% url 'learning_logs:new_topic' %}">Realize a new topic: </a>
		</h3>

{% endblock content %}